# Generated by Django 4.1.8 on 2023-05-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="offer_agreement",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_phone_number",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_agreement",
            field=models.BooleanField(default=True),
        ),
    ]
