# Generated by Django 4.1.8 on 2023-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_offer_agreement_user_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_name", models.CharField(max_length=180)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="interest",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.interest"
            ),
        ),
    ]
