# Generated by Django 4.1.8 on 2023-05-10 09:31

from django.db import migrations, models
import django.db.models.deletion
import halls.models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="address",
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="area",
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="capacity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="condition",
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="phone",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="hall",
            name="site",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="telegram",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="vk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="whatsapp",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="HallMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=halls.models.hall_directory_path)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="halls.hall",
                    ),
                ),
            ],
        ),
    ]
