# Generated by Django 4.1.8 on 2023-04-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="halltype",
            name="hall",
        ),
        migrations.AddField(
            model_name="hall",
            name="hall_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="halls",
                to="halls.halltype",
            ),
        ),
    ]
