# Generated by Django 4.2 on 2023-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_moderate',
            field=models.BooleanField(default=False),
        ),
    ]
