# Generated by Django 4.1.8 on 2023-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0002_hall_address_hall_area_hall_capacity_hall_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
