# Generated by Django 4.2 on 2023-04-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_is_moderate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='is_moderate',
            new_name='is_moderated',
        ),
    ]
