# Generated by Django 4.1.8 on 2023-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0003_remove_hall_hall_type_hall_hall_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="hall_type",
            field=models.ManyToManyField(
                blank=True, related_name="halls", to="halls.halltype"
            ),
        ),
    ]
