# Generated by Django 4.1.8 on 2023-04-19 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("halls", "0004_alter_hall_hall_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="halls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
