# Generated by Django 4.1.8 on 2023-05-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0005_rename_user_hall_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="type",
            new_name="hall_type",
        ),
    ]
