# Generated by Django 4.1.8 on 2023-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0006_rename_type_property_hall_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hallmedia",
            name="is_avatar",
            field=models.BooleanField(default=False),
        ),
    ]
