# Generated by Django 4.1.8 on 2023-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0006_hall_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Boolean", "bool"),
                    ("String", "str"),
                    ("Integer", "int"),
                    ("Fload", "float"),
                ],
                max_length=20,
            ),
        ),
    ]
