# Generated by Django 4.1.8 on 2023-05-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0007_hallmedia_is_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type_name", models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name="hall",
            name="events_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="halls",
                to="halls.eventtype",
            ),
        ),
    ]
