# Generated by Django 4.1.8 on 2023-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0007_alter_property_property_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("bool", "bool"),
                    ("string", "string"),
                    ("int", "int"),
                    ("float", "float"),
                ],
                max_length=20,
            ),
        ),
    ]
