# Generated by Django 4.1.8 on 2023-05-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0008_eventtype_hall_events_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hall",
            old_name="events_type",
            new_name="event_type",
        ),
    ]
