# Generated by Django 4.1.8 on 2023-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0009_rename_events_type_hall_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hall",
            name="event_type",
        ),
        migrations.AddField(
            model_name="hall",
            name="event_type",
            field=models.ManyToManyField(
                null=True, related_name="halls", to="halls.eventtype"
            ),
        ),
    ]
