# Generated by Django 4.1.8 on 2023-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0010_remove_hall_event_type_hall_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="event_type",
            field=models.ManyToManyField(
                blank=True, related_name="halls", to="halls.eventtype"
            ),
        ),
    ]
