# Generated by Django 4.1.8 on 2023-04-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
